const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_CURRENT: "GET_CURRENT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTDETAIL: "GET_PRODUCTDETAIL",
  GET_PRODUCTCATEGORY: "GET_PRODUCTCATEGORY",
  GET_BRAND: "GET_BRAND",
  GET_OPERA: "GET_OPERA",
  GET_USER: "GET_USER",
};
export default actionTypes;
