export const path = {
  HOME: "/*",
  INFO: "tai-khoan",
  ADDRESS: "dia-chi",
  RESETPASSWORD: "mat-khau",
  LOGIN: "/login",
  CART: "Cart",
  CATEGORYPRODUCT: "category-product/:slug",
  SEARCH: "search/:key",
  CATEGORYALL: "categoryAll",
  PAY: "Cart/Pay",
  // admin
  ADMIN: "/admin/*",
  CATEGORY: "/category",
  PRODUCT: "/product",
  Brand: "/brand",
  Opera: "/opera",
  User: "/user",
  TRASHCATEGORY: "/category/trash",
  TRASHPRODUCT: "/product/trash",
  TRANSHBRAND: "/brand/trash",
  TRANSHOPERA: "/opera/trash",
  TRANSHUSER: "/user/trash",
  //client
  PRODUCTDETAIL: "productdetail/:slug",
};
